spring.application.name=backend
spring.datasource.url=jdbc:postgresql://ep-cool-sound-acv4970b-pooler.sa-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_svqaPZ3cOVl1&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datsource.password=npg_bxOGUZX8j1aQ&sslmode

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
